import { readdirSync, writeFileSync, statSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const audioDir = join(__dirname, "..", "public", "audio");
const outputFile = join(__dirname, "..", "src", "data", "sounds.ts");
const manifestFile = join(__dirname, "..", "public", "manifest", "audio-files.json");

function capitalize(name) {
  return name
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function generate() {
  if (!existsSync(audioDir)) {
    console.error("Audio directory not found:", audioDir);
    process.exit(1);
  }

  const entries = readdirSync(audioDir);
  const audioExtensions = new Set([".mp3", ".wav", ".ogg", ".m4a", ".flac", ".aac"]);

  const sounds = entries
    .filter((entry) => {
      const fullPath = join(audioDir, entry);
      return statSync(fullPath).isFile() && audioExtensions.has(entry.toLowerCase().slice(entry.lastIndexOf(".")));
    })
    .map((file) => {
      const name = file.slice(0, file.lastIndexOf("."));
      return {
        id: name,
        title: capitalize(name),
        icon: `/icons/${name}.svg`,
        audio: `/audio/${file}`,
      };
    })
    .sort((a, b) => a.title.localeCompare(b.title));

  const tsContent = `// Auto-generated by scripts/generate-sounds.js
// Do not edit manually.

import type { Sound } from "../types/sound";

export const sounds: Sound[] = ${JSON.stringify(sounds, null, 2)};
`;

  mkdirSync(dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, tsContent, "utf-8");
  console.log(`Generated ${sounds.length} sounds -> src/data/sounds.ts`);

  const audioFiles = sounds.map((s) => s.audio);
  mkdirSync(dirname(manifestFile), { recursive: true });
  writeFileSync(manifestFile, JSON.stringify(audioFiles, null, 2), "utf-8");
  console.log(`Generated audio manifest -> public/manifest/audio-files.json`);
}

generate();
